### PR TITLE
Work with Sonarqube 5.1, add NCLOC metrics

### PR DESCRIPTION
**Pull request by schnee3**
* "Upgrade" for Sonarqube 5.1:
 * Add a "scm" tag in the pom.xml file
 * Remove the line offset when adding a new issue from tslint to sonarqube 

* Add a simple sensor (LOCSensor) that report the NCLOC metrics

### CODE REVIEW

**Comment by DennisJaamann** [comment]
Hello, any update on this?

**Comment by tsjensen** [comment]
Already looking forward to seeing NCLOC metrics ... :smiley:

**Comment by Pablissimo** [comment]
Annoyingly I've not managed to get this merged yet, and after other contributions it'll need a bit of finessing to get in (conflicts exist at the mo). Still, maybe this is the kick-up-the-arse to get it sorted so I'll try and find time next week.

**Comment by Pablissimo** [comment]
Right, I've merged almost all of this (8 months later...) - the one thing I excluded was the 'fix' for attributing issues to line numbers. On my system at least your removal of the +1 causes issues to be reported on the line about where they actually exist. Unsure what's happening there...

**Comment by marcules** [comment]
hi!
Should the LOC value in the (main) dashboard now be filled with this change?

I've rebuilt and reinstalled the plugin with the new sources and started a new analysis, but the value is still empty in the overview. The Project dashboard itself shows the LOC though.

**Comment by Pablissimo** [comment]
Not sure if I'm understanding, but this is the main and project dashboards for my test instance that examines the open-source TypeScriptSnake project:

image

image

Are you not seeing one or other of the two LOC values populated?

**Comment by marcules** [comment]
Hi @Pablissimo 

The two metrics are not filled here. Can you give me some pointers how I'd debug this? I've mvn installed SonarTsPlugin on friday, copied it over the existing plugin, restarted sonar, and triggered a new build of "frontend project a". Here's how the dashboards look like.  

chrome_2016-02-01_10-39-03
chrome_2016-02-01_10-42-35

**Comment by marcules** [comment]
@Pablissimo I'm sorry for the inconvenience, it worked now after I uninstalled. Restarted. Re-Built it. Installed it. Restarted. Made a new run.

Thank you for your great plugin and thanks @schnee3 for this great contribution! :)

**Comment by Pablissimo** [comment]
To be honest I'd have expected it to just run really, with your original steps. But glad you're moving!

**Pull request merged**
