### PR TITLE
Tidy up parameter naming, add samples

### LINKED ISSUE #85: Tidy up parameter naming
Use the SQ parameter name deprecation abilities and restructure parameter names to be more easily readable.

### PR DESCRIPTION
**Pull request by Pablissimo**
* Fixes #85 - tidying up parameter naming
* Adds two new sample projects
* Fixes relative paths output from `tslint` not being parsed properly

### CODE REVIEW

**Comment by nixel2007** [comment]
:+1:

Offtopic: any plans to publish 1.0  to SonarQube update center?

**Comment by Pablissimo** [comment]
Rough plans, but there are so far as I remember specific requirements on your release strategy and documentation that I need to explore first.

**Comment by nixel2007** [comment]
@Pablissimo you can view this (my) thread - https://groups.google.com/forum/#!topic/sonarqube/OLaJrVlft74
And a RFF threads looks like this - https://groups.google.com/forum/#!topic/sonarqube/XnXcHb3R-5A

Feel free to ask any questions, i am glad to help, you plugin is awesome :)

**Comment by Pablissimo** [comment]
Oh that's immensely useful. Thanks!



-------- Original message --------

**Pull request merged**
