### PR TITLE
fix NoClassDefFound errors

### PR DESCRIPTION
**Pull request by stheves**
targeting 6.0 api version and fix NoClassDefFound errors for google guava when using sonarsource sonar-maven-plugin > 3.0, tested with sonarqube server 6.0 alpine

### CODE REVIEW

**Comment by Pablissimo** [comment]
Doesn't targeting 6.0 prevent use on 5.6 LTS?

Presumably this only reproduces when using sonar-maven-plugin, and not when you manually do an analysis from the command line? I've got 5.6, 6.0 and 6.1 installs all running with 0.93 without error at the commandline but don't have a test-case for sonar-maven-plugin yet so that might be my missing link!

**Comment by stheves** [comment]
I don`t think that using the 6.0 API breaks the usage of SonarQube server 5.6 LTS. The JavaScript plugin does exactly the same and it is compatible with 5.6 LTS. See http://docs.sonarqube.org/display/PLUG/JavaScript+Plugin and the 2.17 version of the plugin.

You can only reproduce the error with sonar maven plugin. The error comes in because the LCOVParser uses google guava in line 200 (maybe in others too) and the guava lib is declared as test dependency. Now the guava lib is not available on runtime and you get the NoClassDefFound error. I`ve fixed by explicitely declaring the dependency to sslr-core which bings in the transitive dependency to google guava.

**Comment by Pablissimo** [comment]
Cool, thanks - that's perfect info. To be honest, I'm wondering if I fix it by just removing the dependency entirely, given that it's used for seemingly literally one line in that file and nowhere else but shall investigate.

**Comment by stheves** [comment]
Oh yes that is maybe the better approach. I hadn`t too much time to investigate further, so declaring the dependency was the "quick fix".

**Comment by Pablissimo** [comment]
Equivalent fix to remove the dependency made in the 6.0-supporting rewrite, now available as release v0.94.

**Pull request closed without merging**
