### PR TITLE
Update LCOVParserImpl.java

### PR DESCRIPTION
**Pull request by Pablissimo**
Remove dep on Guava

### CODE REVIEW

**Comment by Pablissimo** [comment]
I think this'll work... I can't get a binary up to GH just now though, and Travis isn't playing ball with uploading to S3 but shall try to get a build up tonight.

**Comment by Pablissimo** [comment]
Re: #59 and #63

**Comment by Pablissimo** [comment]
Ok, how do you get on with this?

[sonar-typescript-plugin-0.94-SNAPSHOT.zip](https://github.com/Pablissimo/SonarTsPlugin/files/557030/sonar-typescript-plugin-0.94-SNAPSHOT.zip)

**Comment by philipooo** [comment]
This works für #63. Thank you very much @Pablissimo!

**Pull request merged**
