### PR TITLE
Add rules remediation

### PR DESCRIPTION
**Pull request by NikitaEgorov**
I'm not a Java developer :)

Add remediation by #9

### CODE REVIEW

**Comment by NikitaEgorov** [comment]
@Pablissimo please merge to master

**Comment by Pablissimo** [comment]
Going to have to wait until next week unfortunately but thanks for the pull request! Only question - where did you get the tech debt times from? I'd intended to keep them in line with the defaults from the Javascript SonarQube plugin, since a lot of the issues are the same so am curious how they compare.

**Comment by NikitaEgorov** [comment]
I get tech debt times from Javascript SonarQube plugin :)

https://github.com/SonarSource/sonar-javascript/tree/master/javascript-checks/src/main/java/org/sonar/javascript/checks

**Comment by Pablissimo** [comment]
Due to the changes that @drywolf made to improve support for custom rules, this specific pull request doesn't really apply - but what I've done is augment @drywolf's work with your technical debt times, so will close this and credit you in the release note!

**Pull request closed without merging**
