### PR TITLE
Fixed issue with tslint standard output of json. 

### PR DESCRIPTION
**Pull request by chintans**
Additional EOL was interfearing with json parsing. Removed that.

`
StreamConsumer stdOutConsumer = new StreamConsumer() {
            public void consumeLine(String line) {
                LOG.trace("TsLint Out: " + line);
                stdOut.append(line,"\n");
            }
        };
`

to 

`
StreamConsumer stdOutConsumer = new StreamConsumer() {
            public void consumeLine(String line) {
                LOG.trace("TsLint Out: " + line);
                stdOut.append(line);
            }
        };
`

### CODE REVIEW

**Comment by chintans** [comment]
This commit helps in fixing #35

**Comment by Pablissimo** [comment]
Thanks for this, will test locally - what was the exception that was being thrown as a result? The same as @NikitaEgorov was seeing in #35?

**Comment by chintans** [comment]
Yes, It fixes issue reported by @NikitaEgorov

**Comment by Pablissimo** [comment]
Cool thanks, will test and merge tonight - annoyingly it's not an issue I can reproduce!

**Pull request merged**
